name: Windows Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - 'package.json'
      - 'renderer/**'
      - '.github/workflows/windows-build.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm install
      - name: Build Windows installer
        run: npm run dist -- --publish=never
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: cs2-case-alerts-windows
          path: |
            dist/*.exe
            dist/*.msi

